import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-black text-white min-h-screen flex">
  {/* SIDEBAR */}
  <aside className="w-64 border-r border-gray-800 p-6 space-y-4">
    <h2 className="text-xl font-bold text-blue-400">Gloreum</h2>

    <nav className="flex flex-col gap-3 text-gray-300">
      <a href="/" className="hover:text-white">Home</a>
      <a href="/ecosystem" className="hover:text-white">Ecosystem</a>
      <a href="/execs" className="hover:text-white">Execs</a>
      <a href="/modules" className="hover:text-white">Modules</a>
      <a href="/documents" className="hover:text-white">Documents</a>
      <a href="/roadmap" className="hover:text-white">Roadmap</a>
      <a href="/governance" className="hover:text-white">Governance</a>
      <a href="/connect" className="hover:text-white">Connect</a>
    </nav>
  </aside>

  {/* MAIN CONTENT */}
  <main className="flex-1">
    {children}
  </main>
</body>
    </html>
  );
}
